import type { CodingChallenge } from './types'

const source = (...lines: string[]): string => lines.join('\n')

const challenges: Record<string, CodingChallenge> = {
    'debounce-throttle': {
        functionName: 'debounce',
        instructions: [
            '只在停止触发 waitMs 后执行',
            '连续调用时使用最后一次参数',
            '保留调用时的 this',
        ],
        starterCode: source('function debounce(fn, waitMs) {', '    // 在这里完成实现', '}'),
        solutionCode: source(
            'function debounce(fn, waitMs) {',
            '    let timer',
            '',
            '    return function (...args) {',
            '        clearTimeout(timer)',
            '        timer = setTimeout(() => fn.apply(this, args), waitMs)',
            '    }',
            '}',
        ),
        testCode: source(
            "test('连续调用只执行最后一次', async () => {",
            '    const calls = []',
            '    const wrapped = debounce((value) => calls.push(value), 20)',
            "    wrapped('first')",
            "    wrapped('last')",
            '    await sleep(45)',
            "    deepEqual(calls, ['last'])",
            '})',
            '',
            "test('能够透传 this 和参数', async () => {",
            '    const target = { base: 4 }',
            '    let result',
            '    target.run = debounce(function (value) { result = this.base + value }, 10)',
            '    target.run(3)',
            '    await sleep(30)',
            '    equal(result, 7)',
            '})',
        ),
    },
    'promise-all': {
        functionName: 'promiseAll',
        instructions: [
            '接受任意 iterable',
            '结果顺序与输入一致',
            '支持普通值和 Promise',
            '空输入立即完成，任一失败时拒绝',
        ],
        starterCode: source('function promiseAll(values) {', '    // 返回一个 Promise', '}'),
        solutionCode: source(
            'function promiseAll(values) {',
            '    const items = Array.from(values)',
            '',
            '    return new Promise((resolve, reject) => {',
            '        if (items.length === 0) {',
            '            resolve([])',
            '            return',
            '        }',
            '',
            '        const results = new Array(items.length)',
            '        let completed = 0',
            '',
            '        items.forEach((item, index) => {',
            '            Promise.resolve(item).then((value) => {',
            '                results[index] = value',
            '                completed += 1',
            '                if (completed === items.length) resolve(results)',
            '            }, reject)',
            '        })',
            '    })',
            '}',
        ),
        testCode: source(
            "test('空输入返回空数组', async () => {",
            '    deepEqual(await promiseAll([]), [])',
            '})',
            '',
            "test('兼容普通值并保持输入顺序', async () => {",
            "    const slow = new Promise((resolve) => setTimeout(() => resolve('slow'), 25))",
            "    const fast = Promise.resolve('fast')",
            "    deepEqual(await promiseAll([slow, 2, fast]), ['slow', 2, 'fast'])",
            '})',
            '',
            "test('任一任务失败时拒绝', async () => {",
            "    await rejects(promiseAll([Promise.resolve(1), Promise.reject(new Error('boom'))]), 'boom')",
            '})',
        ),
    },
    'concurrency-pool': {
        functionName: 'runPool',
        instructions: [
            '任务以函数形式传入，不能提前启动',
            '同时运行数不得超过 limit',
            '结果顺序与任务顺序一致',
            '非法 limit 抛出 RangeError',
        ],
        starterCode: source('async function runPool(tasks, limit) {', '    // 在这里完成实现', '}'),
        solutionCode: source(
            'async function runPool(tasks, limit) {',
            "    if (!Number.isInteger(limit) || limit < 1) throw new RangeError('invalid limit')",
            '',
            '    const results = new Array(tasks.length)',
            '    let nextIndex = 0',
            '',
            '    async function worker() {',
            '        while (nextIndex < tasks.length) {',
            '            const index = nextIndex',
            '            nextIndex += 1',
            '            results[index] = await tasks[index]()',
            '        }',
            '    }',
            '',
            '    const count = Math.min(limit, tasks.length)',
            '    await Promise.all(Array.from({ length: count }, worker))',
            '    return results',
            '}',
        ),
        testCode: source(
            "test('限制并发并保持结果顺序', async () => {",
            '    let active = 0',
            '    let maximum = 0',
            '    const delays = [35, 5, 20, 10]',
            '    const tasks = delays.map((delay, index) => async () => {',
            '        active += 1',
            '        maximum = Math.max(maximum, active)',
            '        await sleep(delay)',
            '        active -= 1',
            '        return index',
            '    })',
            '    deepEqual(await runPool(tasks, 2), [0, 1, 2, 3])',
            '    assert(maximum <= 2, `最大并发数为 ${maximum}`)',
            '})',
            '',
            "test('拒绝非法并发数', async () => {",
            "    await rejects(runPool([], 0), 'invalid limit')",
            '})',
        ),
    },
    'request-race-retry': {
        functionName: 'createLatestRequest',
        instructions: [
            '返回一个可重复调用的异步函数',
            '新调用发起时取消上一次请求',
            '向 request 传入 AbortSignal 和调用参数',
            '只有最新请求可以成功返回',
        ],
        starterCode: source(
            'function createLatestRequest(request) {',
            '    // request 的签名是 request(signal, ...args)',
            '}',
        ),
        solutionCode: source(
            'function createLatestRequest(request) {',
            '    let controller',
            '    let latestId = 0',
            '',
            '    return async (...args) => {',
            '        controller?.abort()',
            '        controller = new AbortController()',
            '        const currentId = ++latestId',
            '',
            '        const value = await request(controller.signal, ...args)',
            '        if (currentId !== latestId) {',
            "            throw new DOMException('Stale request', 'AbortError')",
            '        }',
            '        return value',
            '    }',
            '}',
        ),
        testCode: source(
            "test('新请求取消旧请求', async () => {",
            '    const request = (signal, value, delay) => new Promise((resolve, reject) => {',
            '        const timer = setTimeout(() => resolve(value), delay)',
            "        signal.addEventListener('abort', () => {",
            '            clearTimeout(timer)',
            "            reject(new DOMException('Aborted', 'AbortError'))",
            '        })',
            '    })',
            '    const latest = createLatestRequest(request)',
            "    const oldRequest = latest('old', 40)",
            "    const newRequest = latest('new', 5)",
            "    await rejects(oldRequest, 'Aborted')",
            "    equal(await newRequest, 'new')",
            '})',
        ),
    },
    'event-emitter': {
        functionName: 'EventEmitter',
        instructions: [
            '实现 on、off、emit、once',
            'on 返回取消订阅函数',
            '同一监听函数不重复注册',
            '触发期间修改订阅不影响本轮',
        ],
        starterCode: source('class EventEmitter {', '    // 在这里完成实现', '}'),
        solutionCode: source(
            'class EventEmitter {',
            '    #events = new Map()',
            '',
            '    on(event, listener) {',
            '        const listeners = this.#events.get(event) ?? new Set()',
            '        listeners.add(listener)',
            '        this.#events.set(event, listeners)',
            '        return () => this.off(event, listener)',
            '    }',
            '',
            '    off(event, listener) {',
            '        const listeners = this.#events.get(event)',
            '        listeners?.delete(listener)',
            '        if (listeners?.size === 0) this.#events.delete(event)',
            '    }',
            '',
            '    emit(event, ...args) {',
            '        const listeners = [...(this.#events.get(event) ?? [])]',
            '        listeners.forEach((listener) => listener(...args))',
            '    }',
            '',
            '    once(event, listener) {',
            '        const cancel = this.on(event, (...args) => {',
            '            cancel()',
            '            listener(...args)',
            '        })',
            '        return cancel',
            '    }',
            '}',
        ),
        testCode: source(
            "test('订阅、触发和取消', () => {",
            '    const emitter = new EventEmitter()',
            '    const values = []',
            "    const cancel = emitter.on('change', (value) => values.push(value))",
            "    emitter.emit('change', 1)",
            '    cancel()',
            "    emitter.emit('change', 2)",
            '    deepEqual(values, [1])',
            '})',
            '',
            "test('once 只执行一次', () => {",
            '    const emitter = new EventEmitter()',
            '    let count = 0',
            "    emitter.once('ready', () => { count += 1 })",
            "    emitter.emit('ready')",
            "    emitter.emit('ready')",
            '    equal(count, 1)',
            '})',
        ),
    },
    'array-tree-transform': {
        functionName: 'arrayToTree',
        instructions: [
            '输入节点包含 id 和 parentId',
            '根节点 parentId 为 null',
            '支持子节点出现在父节点之前',
            '不要修改输入对象，孤儿节点不进入结果',
        ],
        starterCode: source('function arrayToTree(items) {', '    // 在这里完成实现', '}'),
        solutionCode: source(
            'function arrayToTree(items) {',
            '    const nodes = new Map(items.map((item) => [',
            '        item.id,',
            '        { ...item, children: [] },',
            '    ]))',
            '    const roots = []',
            '',
            '    for (const node of nodes.values()) {',
            '        if (node.parentId === null) {',
            '            roots.push(node)',
            '            continue',
            '        }',
            '        nodes.get(node.parentId)?.children.push(node)',
            '    }',
            '    return roots',
            '}',
        ),
        testCode: source(
            "test('支持乱序输入并保持输入不可变', () => {",
            '    const items = [',
            "        { id: 2, parentId: 1, name: 'child' },",
            "        { id: 1, parentId: null, name: 'root' },",
            "        { id: 3, parentId: 99, name: 'orphan' },",
            '    ]',
            '    const tree = arrayToTree(items)',
            '    equal(tree.length, 1)',
            "    equal(tree[0].name, 'root')",
            "    equal(tree[0].children[0].name, 'child')",
            "    assert(!('children' in items[0]), '输入对象被修改')",
            '})',
        ),
    },
    'lru-cache': {
        functionName: 'LRUCache',
        instructions: [
            '实现 get 和 set',
            'get 命中后刷新最近使用顺序',
            '超过容量时淘汰最久未使用项',
            '未命中返回 -1',
        ],
        starterCode: source(
            'class LRUCache {',
            '    constructor(capacity) {',
            '        // 在这里初始化',
            '    }',
            '',
            '    get(key) {}',
            '',
            '    set(key, value) {}',
            '}',
        ),
        solutionCode: source(
            'class LRUCache {',
            '    constructor(capacity) {',
            "        if (!Number.isInteger(capacity) || capacity < 1) throw new RangeError('invalid capacity')",
            '        this.capacity = capacity',
            '        this.cache = new Map()',
            '    }',
            '',
            '    get(key) {',
            '        if (!this.cache.has(key)) return -1',
            '        const value = this.cache.get(key)',
            '        this.cache.delete(key)',
            '        this.cache.set(key, value)',
            '        return value',
            '    }',
            '',
            '    set(key, value) {',
            '        this.cache.delete(key)',
            '        this.cache.set(key, value)',
            '        if (this.cache.size > this.capacity) {',
            '            const oldestKey = this.cache.keys().next().value',
            '            this.cache.delete(oldestKey)',
            '        }',
            '    }',
            '}',
        ),
        testCode: source(
            "test('按最近使用顺序淘汰', () => {",
            '    const cache = new LRUCache(2)',
            "    cache.set('a', 1)",
            "    cache.set('b', 2)",
            "    equal(cache.get('a'), 1)",
            "    cache.set('c', 3)",
            "    equal(cache.get('b'), -1)",
            "    equal(cache.get('a'), 1)",
            "    equal(cache.get('c'), 3)",
            '})',
        ),
    },
    'deep-clone-boundaries': {
        functionName: 'deepClone',
        instructions: [
            '支持普通对象、数组、Date、Map 和 Set',
            '使用 WeakMap 处理循环引用',
            '保留同一对象被多处引用的身份关系',
            '支持 Symbol 键',
        ],
        starterCode: source(
            'function deepClone(value, seen = new WeakMap()) {',
            '    // 在这里完成实现',
            '}',
        ),
        solutionCode: source(
            'function deepClone(value, seen = new WeakMap()) {',
            "    if (typeof value !== 'object' || value === null) return value",
            '    if (seen.has(value)) return seen.get(value)',
            '    if (value instanceof Date) return new Date(value)',
            '',
            '    if (value instanceof Map) {',
            '        const copy = new Map()',
            '        seen.set(value, copy)',
            '        value.forEach((item, key) => copy.set(deepClone(key, seen), deepClone(item, seen)))',
            '        return copy',
            '    }',
            '',
            '    if (value instanceof Set) {',
            '        const copy = new Set()',
            '        seen.set(value, copy)',
            '        value.forEach((item) => copy.add(deepClone(item, seen)))',
            '        return copy',
            '    }',
            '',
            '    const copy = Array.isArray(value)',
            '        ? []',
            '        : Object.create(Object.getPrototypeOf(value))',
            '    seen.set(value, copy)',
            '    Reflect.ownKeys(value).forEach((key) => {',
            '        copy[key] = deepClone(value[key], seen)',
            '    })',
            '    return copy',
            '}',
        ),
        testCode: source(
            "test('处理循环引用和共享引用', () => {",
            '    const shared = { value: 1 }',
            '    const input = { first: shared, second: shared }',
            '    input.self = input',
            '    const output = deepClone(input)',
            '    assert(output !== input)',
            '    assert(output.first !== shared)',
            "    assert(output.first === output.second, '共享引用关系丢失')",
            "    assert(output.self === output, '循环引用处理失败')",
            '})',
            '',
            "test('支持 Date、Map、Set 和 Symbol 键', () => {",
            "    const symbol = Symbol('key')",
            '    const input = { date: new Date(0), map: new Map([[1, { ok: true }]]), set: new Set([2]), [symbol]: 3 }',
            '    const output = deepClone(input)',
            '    equal(output.date.getTime(), 0)',
            '    assert(output.map.get(1) !== input.map.get(1))',
            '    assert(output.set.has(2))',
            '    equal(output[symbol], 3)',
            '})',
        ),
    },
    'call-apply-bind': {
        functionName: 'bind',
        instructions: [
            '返回一个新函数，调用时 this 为绑定的对象',
            '支持预设参数，后调用的参数接在后面',
            '原函数的返回值要原样传出',
        ],
        starterCode: source(
            'function bind(fn, context, ...prefix) {',
            '    // 返回绑定后的函数',
            '}',
        ),
        solutionCode: source(
            'function bind(fn, context, ...prefix) {',
            "    if (typeof fn !== 'function') throw new TypeError('bind target must be a function')",
            '',
            '    return function bound(...rest) {',
            '        return fn.apply(context, [...prefix, ...rest])',
            '    }',
            '}',
        ),
        testCode: source(
            "test('绑定 this 并返回原函数结果', () => {",
            '    const target = { base: 10 }',
            '    function add(value) { return this.base + value }',
            '    const bound = bind(add, target)',
            '    equal(bound(5), 15)',
            '})',
            '',
            "test('预设参数与后续参数按顺序拼接', () => {",
            '    const calls = []',
            '    function collect(a, b, c) { calls.push([this.id, a, b, c]) }',
            "    const bound = bind(collect, { id: 'ctx' }, 1)",
            '    bound(2, 3)',
            "    deepEqual(calls, [['ctx', 1, 2, 3]])",
            '})',
            '',
            "test('非函数目标应抛错', () => {",
            '    let thrown = false',
            '    try { bind(null, {}) } catch (error) { thrown = error instanceof TypeError }',
            '    assert(thrown)',
            '})',
        ),
    },
    'array-flatten': {
        functionName: 'flatten',
        instructions: [
            '按 depth 展开嵌套数组，默认完全展开',
            'depth 为 0 或负数时返回浅拷贝',
            '不修改原数组，非数组元素保持原样',
        ],
        starterCode: source('function flatten(input, depth) {', '    // 返回新数组', '}'),
        solutionCode: source(
            'function flatten(input, depth = Infinity) {',
            '    if (!Array.isArray(input)) throw new TypeError("flatten expects an array")',
            '    const maxDepth = depth === undefined ? Infinity : Number(depth)',
            '    if (Number.isNaN(maxDepth) || maxDepth <= 0) return input.slice()',
            '',
            '    const output = []',
            '    for (let index = 0; index < input.length; index += 1) {',
            '        if (!(index in input)) continue',
            '        const item = input[index]',
            '        if (Array.isArray(item)) output.push(...flatten(item, maxDepth - 1))',
            '        else output.push(item)',
            '    }',
            '    return output',
            '}',
        ),
        testCode: source(
            "test('默认完全展开', () => {",
            '    deepEqual(flatten([1, [2, [3, 4]], 5]), [1, 2, 3, 4, 5])',
            '})',
            '',
            "test('按深度展开且不改原数组', () => {",
            '    const input = [1, [2, [3]]]',
            '    deepEqual(flatten(input, 1), [1, 2, [3]])',
            '    deepEqual(input, [1, [2, [3]]])',
            '})',
            '',
            "test('depth 为 0 时返回浅拷贝', () => {",
            '    const input = [[1]]',
            '    const output = flatten(input, 0)',
            '    deepEqual(output, [[1]])',
            '    assert(output !== input)',
            '})',
        ),
    },
}

export function getHandwritingChallenge(slug: string): CodingChallenge | undefined {
    return challenges[slug]
}
